apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  contact-points: {{ .Values.cassandra.contactPoints }}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  username: {{ .Values.cassandra.user | b64enc | quote }}
  password: {{ .Values.cassandra.password | b64enc | quote }}