apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
  {{- include "notification-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "notification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "notification-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
        env:
        - name: kafka.bootstrap-address
          value: {{ .Values.kafka.bootstrapAddress }}
        ports:
        - name: {{ .Values.service.targetPort }}
          containerPort: 8084
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
