server:
  port: 8081

spring:
  data:
    cassandra:
      port: 9042
      contact-points: localhost
      local-datacenter: datacenter1
      keyspace-name: user_service
      username: user_service
      password: user_service

management:
  endpoint:
    health:
      probes:
        enabled: true