server:
  port: 8083

spring:
  data:
    cassandra:
      port: 9042
      contact-points: localhost
      local-datacenter: datacenter1
      keyspace-name: order_service
      username: order_service
      password: order_service

management:
  endpoint:
    health:
      probes:
        enabled: true

kafka:
  bootstrap-address: "localhost:9092"
