replicaCount: 1

image: lkuzmicheva/auth-service

service:
  type: ClusterIP
  port: 9000
  targetPort: web

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $1
  hosts:
    - host: arch.homework
      paths: ["/otusapp/kuzmicheva(/auth/.*|/auth$)"]

cassandra:
  user: auth_service
  password: auth_service
  contactPoints: cassandra

userservice:
  url: "http://user-service.myapp.svc.cluster.local:9001"
