apiVersion: v1
kind: Secret
metadata:
  name: billing-service-secret
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}