apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "billing-service.fullname" . }}
  labels:
  {{- include "billing-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "billing-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "billing-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
        env:
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: billing-service-secret
              key: username
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: billing-service-secret
              key: password
        - name: spring.datasource.url
          value: {{ .Values.postgresql.url }}
        - name: kafka.bootstrap-address
          value: {{ .Values.kafka.bootstrapAddress }}
        ports:
        - name: {{ .Values.service.targetPort }}
          containerPort: 8082
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
