apiVersion: v1
kind: Service
metadata:
  name: {{ include "billing-service.fullname" . }}
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: web
    protocol: TCP
  selector:
    {{- include "billing-service.selectorLabels" . | nindent 4 }}
