replicaCount: 1

image: lkuzmicheva/billing-service

service:
  type: ClusterIP
  port: 9002
  targetPort: web

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $1
    nginx.ingress.kubernetes.io/auth-url: "http://auth-service.myapp.svc.cluster.local:9000/auth"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Client,X-Auth-Roles"
  hosts:
    - host: arch.homework
      paths: ["/otusapp/kuzmicheva(/billing/.*|/billing$)"]

postgresql:
  url: jdbc:postgresql://postgresql:5432/postgres
  username: postgres
  password: postgres

kafka:
  bootstrapAddress: "http://kafka.myapp.svc.cluster.local:9092"